name: PC Windows Virtual

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Testar Windows
        shell: pwsh
        run: |
          Write-Host "Windows iniciado!"
          Get-ComputerInfo |
            Select-Object WindowsProductName,
                          WindowsVersion
